AWSTemplateFormatVersion: "2010-09-09"
Description: Import test

Parameters:
  ImageTag:
    Type: String
    Default: latest
    Description: Enter docker image tag.

Resources:
  # sunscription filter for lambda
  LogsSubscriptionFilter:
    Type: "AWS::Logs::SubscriptionFilter"
    DeletionPolicy: Delete
    Properties:
      LogGroupName: /aws/lambda/lambda-for-test
      FilterPattern: "ERROR"
      DestinationArn: !GetAtt PublishToSNSLambdaFunction.Arn

  # publish to sns function
  PublishToSNSLambdaFunction:
    Type: "AWS::Lambda::Function"
    DeletionPolicy: Delete
    Properties:
      Description: ""
      FunctionName: "publish-to-sns"
      Code:
        ImageUri:
          Fn::Join:
            - ":"
            - - !Sub "${AWS::AccountId}.dkr.ecr.ap-northeast-1.amazonaws.com/ecr-for-test"
              - Ref: ImageTag
      PackageType: Image
      MemorySize: 128
      Role: !GetAtt PublishToSNSIAMRole.Arn
      Timeout: 3
      TracingConfig:
        Mode: "PassThrough"

  # permission for subscribe cloudwatch logs
  Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt PublishToSNSLambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: logs.ap-northeast-1.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"
      SourceArn: !Sub "arn:aws:logs:ap-northeast-1:${AWS::AccountId}:log-group:*:*"

  # SNS Topic
  SNSTopic:
    Type: "AWS::SNS::Topic"
    DeletionPolicy: Delete
    Properties:
      DisplayName: ""
      TopicName: "alert-notification"

  # SNS Subscription
  SNSSubscription:
    Type: "AWS::SNS::Subscription"
    DeletionPolicy: Delete
    Properties:
      Endpoint: !GetAtt SendToSlackLambdaFunction.Arn
      Protocol: lambda
      TopicArn: !Ref SNSTopic

  # send to slack function
  SendToSlackLambdaFunction:
    Type: "AWS::Lambda::Function"
    DeletionPolicy: Delete
    Properties:
      Description: ""
      FunctionName: "send-to-slack"
      Code:
        ImageUri:
          Fn::Join:
            - ":"
            - - !Sub "${AWS::AccountId}.dkr.ecr.ap-northeast-1.amazonaws.com/ecr-for-test"
              - Ref: ImageTag
      PackageType: Image
      MemorySize: 128
      Role: !GetAtt SendToSlackIAMRole.Arn
      Timeout: 3
      TracingConfig:
        Mode: "PassThrough"

  # IAM role for lambda
  PublishToSNSIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/service-role/"
      RoleName: "publish-to-sns-lambda-role"
      AssumeRolePolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":"lambda.amazonaws.com"},"Action":"sts:AssumeRole"}]}'
      MaxSessionDuration: 3600
      ManagedPolicyArns:
        - !Ref PublishToSNSIAMManagedPolicy
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess

  SendToSlackIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/service-role/"
      RoleName: "send-to-slack-lambda-role"
      AssumeRolePolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":"lambda.amazonaws.com"},"Action":"sts:AssumeRole"}]}'
      MaxSessionDuration: 3600
      ManagedPolicyArns:
        - !Ref SendToSlackIAMManagedPolicy

  PublishToSNSIAMManagedPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: "publish-to-sns-lambda-policy"
      Path: "/service-role/"
      PolicyDocument: !Sub |
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Action": "logs:CreateLogGroup",
                    "Resource": "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
                },
                {
                    "Effect": "Allow",
                    "Action": [
                        "logs:CreateLogStream",
                        "logs:PutLogEvents"
                    ],
                    "Resource": [
                        "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/publish-to-sns:*"
                    ]
                }
            ]
        }

  SendToSlackIAMManagedPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: "send-to-slack-lambda-policy"
      Path: "/service-role/"
      PolicyDocument: !Sub |
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Action": "logs:CreateLogGroup",
                    "Resource": "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
                },
                {
                    "Effect": "Allow",
                    "Action": [
                        "logs:CreateLogStream",
                        "logs:PutLogEvents"
                    ],
                    "Resource": [
                        "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/send-to-slack:*"
                    ]
                }
            ]
        }
