AWSTemplateFormatVersion: "2010-09-09"
Description: Import test

Parameters:
  ImageTag:
    Type: String
    Default: latest
    Description: Enter docker image tag.

Resources:
  # sunscription filter for lambda
  LogsSubscriptionFilter:
    Type: "AWS::Logs::SubscriptionFilter"
    DeletionPolicy: Delete
    Properties:
      LogGroupName: /aws/lambda/lambda-for-test
      FilterPattern: "ERROR"
      DestinationArn: !GetAtt PublishToSNSLambdaFunction.Arn

  # publish to sns function
  PublishToSNSLambdaFunction:
    Type: "AWS::Lambda::Function"
    DeletionPolicy: Delete
    Properties:
      Description: ""
      FunctionName: "publish-to-sns"
      Code:
        ImageUri:
          Fn::Join:
            - ":"
            - - !Sub "${AWS::AccountId}.dkr.ecr.ap-northeast-1.amazonaws.com/ecr-for-test"
              - Ref: ImageTag
      PackageType: Image
      MemorySize: 128
      # TODO: create role for this purpuse
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/test-role-jkvt52rs"
      Timeout: 3
      TracingConfig:
        Mode: "PassThrough"

  # permission for subscribe cloudwatch logs
  Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt PublishToSNSLambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: logs.ap-northeast-1.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"
      SourceArn: !Sub "arn:aws:logs:ap-northeast-1:${AWS::AccountId}:log-group:*:*"

  # SNS Topic
  SNSTopic:
    Type: "AWS::SNS::Topic"
    DeletionPolicy: Delete
    Properties:
      DisplayName: ""
      TopicName: "alert-notification"

  # SNS Subscription
  SNSSubscription:
    Type: "AWS::SNS::Subscription"
    DeletionPolicy: Delete
    Properties:
      Endpoint: !GetAtt SendToSlackLambdaFunction.Arn
      Protocol: lambda
      TopicArn: !Ref SNSTopic

  # send to slack function
  SendToSlackLambdaFunction:
    Type: "AWS::Lambda::Function"
    DeletionPolicy: Delete
    Properties:
      Description: ""
      FunctionName: "send-to-slack"
      Code:
        ImageUri:
          Fn::Join:
            - ":"
            - - !Sub "${AWS::AccountId}.dkr.ecr.ap-northeast-1.amazonaws.com/ecr-for-test"
              - Ref: ImageTag
      PackageType: Image
      MemorySize: 128
      # TODO: create role for this purpuse
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/test-role-jkvt52rs"
      Timeout: 3
      TracingConfig:
        Mode: "PassThrough"
