AWSTemplateFormatVersion: "2010-09-09"
Description: "ECR for alert notification"
Resources:
  PublishToSNSECRRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "publish-to-sns"
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
              "rules": [
                  {
                      "rulePriority": 1,
                      "description": "Delete more than 20 images",
                      "selection": {
                          "tagStatus": "any",
                          "countType": "imageCountMoreThan",
                          "countNumber": 20
                      },
                      "action": {
                          "type": "expire"
                      }
                  }
              ]
          }

  SendToSlackECRRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "send-to-slack"
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
              "rules": [
                  {
                      "rulePriority": 1,
                      "description": "Delete more than 20 images",
                      "selection": {
                          "tagStatus": "any",
                          "countType": "imageCountMoreThan",
                          "countNumber": 20
                      },
                      "action": {
                          "type": "expire"
                      }
                  }
              ]
          }

Outputs:
  PublishToSNSECRRepositoryName:
    Description: "Name of Publish To SNS Repository"
    Value: !Ref PublishToSNSECRRepository
    Export:
      Name: !Sub "${AWS::StackName}-PublishToSNSECRRepositoryName"
  SendToSlackECRRepositoryName:
    Description: "Name of Send To Slack Repository"
    Value: !Ref SendToSlackECRRepository
    Export:
      Name: !Sub "${AWS::StackName}-SendToSlackECRRepositoryName"
